# Generated by Django 5.2.3 on 2025-06-19 00:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HashingLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_type', models.CharField(choices=[('chaining', 'Encadenamiento'), ('linear_probing', 'Sondeo Lineal'), ('quadratic_probing', 'Sondeo Cuadrático'), ('double_hashing', 'Doble Hashing')], max_length=50)),
                ('operation_type', models.CharField(choices=[('insert', 'Insertar'), ('search', 'Buscar')], max_length=10)),
                ('key', models.CharField(max_length=255)),
                ('value', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(default=django.utils.timezone.now)),
                ('result', models.TextField(blank=True, null=True)),
                ('table_state_json', models.JSONField(default=dict)),
                ('collisions', models.IntegerField(default=0)),
                ('probes', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='HashTableSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('algorithm_type', models.CharField(choices=[('chaining', 'Encadenamiento'), ('linear_probing', 'Sondeo Lineal'), ('quadratic_probing', 'Sondeo Cuadrático'), ('double_hashing', 'Doble Hashing')], max_length=50)),
                ('slot_index', models.IntegerField()),
                ('key_value', models.CharField(blank=True, max_length=255, null=True)),
                ('actual_value', models.TextField(blank=True, null=True)),
            ],
            options={
                'unique_together': {('algorithm_type', 'slot_index')},
            },
        ),
        migrations.CreateModel(
            name='ChainedElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key_value', models.CharField(max_length=255)),
                ('actual_value', models.TextField()),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chained_elements', to='hashing_app.hashtableslot')),
            ],
            options={
                'unique_together': {('slot', 'key_value')},
            },
        ),
    ]
